import hashlib
import logging
import os
import tempfile
import uuid
import zoneinfo
from contextlib import suppress
from datetime import datetime, time
from html import escape
from types import SimpleNamespace
from typing import Any

from telegram import ForceReply, ReplyParameters, Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import (
    Application,
    ApplicationBuilder,
    CallbackQueryHandler,
    CommandHandler,
    ContextTypes,
    MessageHandler,
    filters,
)

from config import settings
from services.formatter import format_entry
from services.notion import save_entry
from services.state_store import state_store
from services.summary import generate_daily_summary, generate_weekly_report
from services.whisper import transcribe

logging.basicConfig(
    format="%(asctime)s [%(levelname)s] %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger(__name__)
logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("httpcore").setLevel(logging.WARNING)

DRAFTS_KEY = "drafts"
EDIT_PROMPTS_KEY = "edit_prompts"
MAX_CONCURRENT_UPDATES = 1024
STARTUP_REPLAY_LIMIT = 10

WELCOME_TEXT = """👋 Welcome to Noter!

I turn your voice or text messages into structured diary entries in Notion.

Send me a voice or text message and I'll:
• Transcribe voice
• Format it into a title and clean text
• Let you review and edit before saving
• Save it to your Notion journal

Every day at 21:00 I'll send you a summary of the day.

Type /help to see detailed instructions."""

HELP_TEXT = """*How to use Noter*

1. Send a voice or text message — speak naturally, I'll handle the rest
2. Review the preview:
   • *Title* — short heading generated by AI
   • *Text* — cleaned up transcription
   • *Tags* — auto-extracted + `Daily` (always added)
3. Edit anything using the buttons
4. Press *✓ Save* to send to Notion

*Editing*
*✎ Title* — send a new title
*✎ Text* — send a new text
*✎ Tags* — send tags separated by commas: `sport, health, work`

*Daily summary*
Every day at 21:00 I send a summary of all entries recorded that day. If there are none, I'll send a friendly nudge instead."""


def _tags_html(tags: list[str]) -> str:
    all_tags = ["Daily"] + [t for t in tags if t != "Daily"]
    return " ".join(f"<code>{escape(t)}</code>" for t in all_tags)


def _preview_text(title: str, text: str, tags: list[str]) -> str:
    return "\n\n".join([
        f"<b>{escape(title)}</b>",
        escape(text),
        _tags_html(tags),
    ])


def _preview_msg_id(draft: dict) -> int:
    return draft.get("preview_msg_id") or draft.get("title_msg_id") or draft["buttons_msg_id"]


def _new_entry_id() -> str:
    return uuid.uuid4().hex[:12]


def _drafts(context: ContextTypes.DEFAULT_TYPE) -> dict:
    return context.user_data.setdefault(DRAFTS_KEY, {})


def _edit_prompts(context: ContextTypes.DEFAULT_TYPE) -> dict:
    return context.user_data.setdefault(EDIT_PROMPTS_KEY, {})


def _prompt_key(chat_id: int, message_id: int) -> str:
    return f"{chat_id}:{message_id}"


def _message_date(message) -> str | None:
    date = getattr(message, "date", None)
    if isinstance(date, datetime):
        return date.isoformat()
    return None


def _source_text_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _entry_metadata(record: dict | None, source_text: str) -> dict:
    if not record:
        return {}

    metadata = {
        "source": record.get("kind"),
        "telegram_chat_id": record.get("chat_id"),
        "telegram_message_id": record.get("message_id"),
    }
    if record.get("kind") == "voice":
        metadata.update({
            "voice_file_unique_id": record.get("file_unique_id"),
            "audio_duration": record.get("duration"),
            "audio_file_size": record.get("file_size"),
        })
    elif record.get("kind") == "text":
        metadata["source_text_hash"] = _source_text_hash(source_text)
    return {key: value for key, value in metadata.items() if value is not None}


def _get_draft(context: ContextTypes.DEFAULT_TYPE, entry_id: str) -> dict[str, Any] | None:
    draft = _drafts(context).get(entry_id)
    if draft:
        return draft

    draft = state_store.get_draft(entry_id)
    if draft:
        _drafts(context)[entry_id] = draft
    return draft


def _preview_keyboard(entry_id: str, highlighted: bool = False) -> InlineKeyboardMarkup:
    highlight_btn = (
        InlineKeyboardButton("⭐ Highlighted", callback_data=f"toggle_highlight:{entry_id}")
        if highlighted else
        InlineKeyboardButton("Mark as Highlight ⭐", callback_data=f"toggle_highlight:{entry_id}")
    )
    return InlineKeyboardMarkup([
        [
            InlineKeyboardButton("✎ Title", callback_data=f"edit_title:{entry_id}"),
            InlineKeyboardButton("✎ Text", callback_data=f"edit_text:{entry_id}"),
            InlineKeyboardButton("✎ Tags", callback_data=f"edit_tags:{entry_id}"),
        ],
        [highlight_btn],
        [InlineKeyboardButton("✓ Save", callback_data=f"save:{entry_id}")],
        [InlineKeyboardButton("Cancel", callback_data=f"cancel:{entry_id}")],
    ])


def _message_chat_id(message) -> int:
    chat_id = getattr(message, "chat_id", None)
    if chat_id is not None:
        return chat_id
    return message.chat.id


async def _edit_reply_message(
    context: ContextTypes.DEFAULT_TYPE,
    message,
    text: str,
    **kwargs,
):
    return await context.bot.edit_message_text(
        chat_id=_message_chat_id(message),
        message_id=message.message_id,
        text=text,
        **kwargs,
    )


class StoredMessageRef:
    def __init__(self, bot, chat_id: int, message_id: int) -> None:
        self.bot = bot
        self.chat_id = chat_id
        self.message_id = message_id


async def _reply_to_source(message_ref, text: str, **kwargs):
    bot = message_ref.bot if isinstance(message_ref, StoredMessageRef) else message_ref.get_bot()
    return await bot.send_message(
        chat_id=_message_chat_id(message_ref),
        text=text,
        reply_parameters=ReplyParameters(
            message_id=message_ref.message_id,
            allow_sending_without_reply=True,
        ),
        **kwargs,
    )


async def replay_unprocessed_messages(application: Application) -> None:
    records = state_store.recent_unprocessed_messages(STARTUP_REPLAY_LIMIT)
    if not records:
        return

    logger.info("Replaying %d unprocessed message(s) after restart", len(records))
    for record in records:
        message_ref = StoredMessageRef(
            application.bot,
            chat_id=record["chat_id"],
            message_id=record["message_id"],
        )
        context = SimpleNamespace(
            application=application,
            bot=application.bot,
            user_data={},
        )
        application.create_task(
            _process_message_record(record["key"], message_ref, context),
        )


async def handle_start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.effective_message.reply_text(WELCOME_TEXT)


async def handle_help(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.effective_message.reply_text(HELP_TEXT, parse_mode="Markdown")


async def handle_voice(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    message = update.effective_message
    voice = message.voice
    message_key = state_store.record_voice(
        chat_id=message.chat_id,
        message_id=message.message_id,
        file_id=voice.file_id,
        date=_message_date(message),
        file_unique_id=getattr(voice, "file_unique_id", None),
        duration=getattr(voice, "duration", None),
        file_size=getattr(voice, "file_size", None),
    )
    context.application.create_task(
        _process_message_record(message_key, message, context),
        update=update,
    )


async def handle_text(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    message = update.effective_message
    message_key = state_store.record_text(
        chat_id=message.chat_id,
        message_id=message.message_id,
        text=message.text,
        date=_message_date(message),
    )
    context.application.create_task(
        _process_message_record(message_key, message, context),
        update=update,
    )


async def _process_message_record(
    message_key: str,
    message_ref,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    record = state_store.get_message(message_key)
    if not record or record.get("status") in {"drafted", "saved"}:
        return

    state_store.mark_message_processing(message_key)
    if record["kind"] == "voice":
        await _process_voice_record(record, message_ref, context)
    elif record["kind"] == "text":
        await _process_text_record(record, message_ref, context)


async def _process_voice_record(
    record: dict[str, Any],
    message_ref,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    tmp_path = None
    status_msg = None
    try:
        status_msg = await _reply_to_source(message_ref, "Listening...")

        voice_file = await context.bot.get_file(record["file_id"])
        with tempfile.NamedTemporaryFile(suffix=".ogg", delete=False) as tmp:
            tmp_path = tmp.name
        await voice_file.download_to_drive(tmp_path)

        await _edit_reply_message(context, status_msg, "Transcribing...")
        transcription = (await transcribe(tmp_path)).strip()
        logger.info(
            "Transcription with %s: %s",
            settings.openai_transcription_model,
            transcription,
        )
        if not transcription:
            state_store.mark_message_failed(
                record["key"],
                f"{settings.openai_transcription_model} returned an empty transcription",
            )
            await _edit_reply_message(
                context,
                status_msg,
                f"{settings.openai_transcription_model} did not recognize any speech in this message."
            )
            return

        await _edit_reply_message(context, status_msg, f"Formatting with {settings.openai_formatter_model}...")
        await _create_preview(
            message_ref,
            context,
            transcription,
            message_key=record["key"],
            preview_message=status_msg,
        )

    except Exception as e:
        logger.exception("Error processing voice message")
        state_store.mark_message_failed(record["key"], str(e))
        if status_msg:
            await _edit_reply_message(context, status_msg, f"Error: {e}")
        else:
            await _reply_to_source(message_ref, f"Error: {e}")
    finally:
        if tmp_path:
            with suppress(FileNotFoundError):
                os.unlink(tmp_path)


async def _process_text_record(
    record: dict[str, Any],
    message_ref,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    status_msg = None
    try:
        status_msg = await _reply_to_source(message_ref, "Formatting...")
        await _create_preview(
            message_ref,
            context,
            record["text"],
            message_key=record["key"],
            preview_message=status_msg,
        )
    except Exception as e:
        logger.exception("Error processing text message")
        state_store.mark_message_failed(record["key"], str(e))
        if status_msg:
            await _edit_reply_message(context, status_msg, f"Error: {e}")
        else:
            await _reply_to_source(message_ref, f"Error: {e}")


async def _create_preview(
    message,
    context: ContextTypes.DEFAULT_TYPE,
    source_text: str,
    message_key: str | None = None,
    preview_message=None,
) -> None:
    title, text, tags = await format_entry(source_text)
    entry_id = _new_entry_id()

    preview = _preview_text(title, text, tags)
    keyboard = _preview_keyboard(entry_id, highlighted=False)
    if preview_message:
        preview_msg = preview_message
        await _edit_reply_message(
            context,
            preview_msg,
            preview,
            parse_mode="HTML",
            reply_markup=keyboard,
        )
    else:
        preview_msg = await _reply_to_source(
            message,
            preview,
            parse_mode="HTML",
            reply_markup=keyboard,
        )

    _drafts(context)[entry_id] = {
        "id": entry_id,
        "title": title,
        "text": text,
        "tags": tags,
        "metadata": _entry_metadata(state_store.get_message(message_key) if message_key else None, source_text),
        "chat_id": message.chat_id,
        "preview_msg_id": preview_msg.message_id,
        "saving": False,
        "message_key": message_key,
    }
    state_store.save_draft(_drafts(context)[entry_id])
    if message_key:
        state_store.mark_message_drafted(message_key, entry_id)


def _callback_payload(update: Update) -> tuple[str, str] | tuple[None, None]:
    data = update.callback_query.data or ""
    if ":" not in data:
        return None, None
    action, entry_id = data.split(":", 1)
    return action, entry_id


async def entry_callback(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    query = update.callback_query
    await query.answer()

    action, entry_id = _callback_payload(update)
    draft = _get_draft(context, entry_id)
    if not action or not draft:
        await query.message.reply_text("This draft is no longer available.")
        return

    if draft.get("saving") and action != "save":
        await query.message.reply_text("This draft is already saving.")
        return

    if action == "save":
        await _save_draft(query, context, entry_id, draft)
    elif action == "cancel":
        await _cancel_draft(query, context, entry_id, draft)
    elif action == "toggle_highlight":
        await _toggle_highlight(context, draft)
    elif action in {"edit_title", "edit_text", "edit_tags"}:
        await _request_edit(query, context, entry_id, action.removeprefix("edit_"))


async def _save_draft(query, context: ContextTypes.DEFAULT_TYPE, entry_id: str, draft: dict) -> None:
    if draft.get("saving"):
        return

    draft["saving"] = True
    try:
        await query.edit_message_text("Saving to Notion...")
        result = await save_entry(
            draft["title"],
            draft["text"],
            draft["tags"],
            draft.get("metadata"),
        )
        if result.created:
            await query.edit_message_text("✓ Saved to Notion and verified")
        else:
            await query.edit_message_text("✓ Already saved in Notion")
    except Exception as e:
        logger.exception("Error saving to Notion")
        draft["saving"] = False
        state_store.save_draft(draft)
        await query.edit_message_text(
            f"Not saved to Notion: {e}\nDraft kept. Press Save to retry or Cancel to discard.",
            reply_markup=_preview_keyboard(entry_id, highlighted=draft["title"].startswith("⭐ ")),
        )
        return

    _drafts(context).pop(entry_id, None)
    state_store.mark_message_saved(draft.get("message_key"))
    state_store.remove_draft(entry_id)


async def _cancel_draft(query, context: ContextTypes.DEFAULT_TYPE, entry_id: str, draft: dict) -> None:
    _drafts(context).pop(entry_id, None)
    state_store.mark_message_cancelled(draft.get("message_key"))
    state_store.remove_draft(entry_id)
    await query.edit_message_text("Cancelled.")


async def _toggle_highlight(context: ContextTypes.DEFAULT_TYPE, draft: dict) -> None:
    highlighted = draft["title"].startswith("⭐ ")
    if highlighted:
        draft["title"] = draft["title"][len("⭐ "):]
    else:
        draft["title"] = f"⭐ {draft['title']}"
    state_store.save_draft(draft)

    highlighted = not highlighted
    await context.bot.edit_message_text(
        chat_id=draft["chat_id"],
        message_id=_preview_msg_id(draft),
        text=_preview_text(draft["title"], draft["text"], draft["tags"]),
        parse_mode="HTML",
        reply_markup=_preview_keyboard(draft["id"], highlighted=highlighted),
    )


async def _request_edit(query, context: ContextTypes.DEFAULT_TYPE, entry_id: str, field: str) -> None:
    labels = {
        "title": "Send a new title:",
        "text": "Send a new text:",
        "tags": "Send tags separated by commas:",
    }
    prompt = await query.message.reply_text(
        labels[field],
        reply_markup=ForceReply(selective=True),
    )
    _edit_prompts(context)[_prompt_key(query.message.chat_id, prompt.message_id)] = {
        "entry_id": entry_id,
        "field": field,
    }


async def receive_edit_reply(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    user_msg = update.effective_message
    reply_to = user_msg.reply_to_message
    if not reply_to:
        await handle_text(update, context)
        return

    chat_id = update.effective_chat.id
    prompt_id = reply_to.message_id
    prompt = _edit_prompts(context).pop(_prompt_key(chat_id, prompt_id), None)
    if not prompt:
        await handle_text(update, context)
        return

    draft = _get_draft(context, prompt["entry_id"])
    if not draft:
        await user_msg.reply_text("This draft is no longer available.")
        return

    field = prompt["field"]
    if field == "title":
        draft["title"] = user_msg.text.strip()
    elif field == "text":
        draft["text"] = user_msg.text.strip()
    elif field == "tags":
        draft["tags"] = [t.strip() for t in user_msg.text.split(",") if t.strip()]

    state_store.save_draft(draft)
    await context.bot.edit_message_text(
        chat_id=chat_id,
        message_id=_preview_msg_id(draft),
        text=_preview_text(draft["title"], draft["text"], draft["tags"]),
        parse_mode="HTML",
        reply_markup=_preview_keyboard(prompt["entry_id"], highlighted=draft["title"].startswith("⭐ ")),
    )
    with suppress(Exception):
        await context.bot.delete_message(chat_id, prompt_id)
    with suppress(Exception):
        await context.bot.delete_message(chat_id, user_msg.message_id)


async def handle_weekly(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.effective_message.reply_text("Generating weekly report...")
    try:
        report = await generate_weekly_report()
        if report:
            await update.effective_message.reply_text(
                f"*Weekly highlights*\n\n{report}",
                parse_mode="Markdown",
            )
        else:
            await update.effective_message.reply_text("No entries this week.")
    except Exception:
        logger.exception("Error generating weekly report")
        await update.effective_message.reply_text("Error generating weekly report.")


async def send_weekly_report(context: ContextTypes.DEFAULT_TYPE) -> None:
    logger.info("Generating weekly report...")
    try:
        report = await generate_weekly_report()
        if report:
            await context.bot.send_message(
                chat_id=settings.allowed_user_id,
                text=f"*Weekly highlights*\n\n{report}",
                parse_mode="Markdown",
            )
        else:
            await context.bot.send_message(
                chat_id=settings.allowed_user_id,
                text="No entries this week — next week is a fresh start!",
            )
    except Exception:
        logger.exception("Error generating weekly report")


async def send_daily_summary(context: ContextTypes.DEFAULT_TYPE) -> None:
    logger.info("Generating daily summary...")
    try:
        summary = await generate_daily_summary()
        if summary:
            await context.bot.send_message(
                chat_id=settings.allowed_user_id,
                text=f"*Daily summary*\n\n{summary}",
                parse_mode="Markdown",
            )
        else:
            await context.bot.send_message(
                chat_id=settings.allowed_user_id,
                text="Hey, how was your day? I'm sure you have something to be proud of!",
            )
    except Exception:
        logger.exception("Error generating daily summary")


def main() -> None:
    app = (
        ApplicationBuilder()
        .token(settings.telegram_token)
        .concurrent_updates(MAX_CONCURRENT_UPDATES)
        .post_init(replay_unprocessed_messages)
        .build()
    )

    user_filter = filters.User(user_id=settings.allowed_user_id)

    command_handlers = [
        CommandHandler("start", handle_start, filters=user_filter),
        CommandHandler("help", handle_help, filters=user_filter),
        CommandHandler("weekly", handle_weekly, filters=user_filter),
    ]

    for handler in command_handlers:
        app.add_handler(handler)
    app.add_handler(MessageHandler(filters.VOICE & user_filter, handle_voice))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND & filters.REPLY & user_filter, receive_edit_reply))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND & user_filter, handle_text))
    app.add_handler(
        CallbackQueryHandler(
            entry_callback,
            pattern="^(save|cancel|toggle_highlight|edit_title|edit_text|edit_tags):",
        )
    )

    tz = zoneinfo.ZoneInfo(settings.timezone)
    app.job_queue.run_daily(
        send_daily_summary,
        time=time(21, 0, tzinfo=tz),
    )
    app.job_queue.run_daily(
        send_weekly_report,
        time=time(21, 0, tzinfo=tz),
        days=(6,),  # Sunday only
    )

    logger.info("Bot started")
    app.run_polling()


if __name__ == "__main__":
    main()
